- hosts: worker
  vars:
  - pname: "docker-ce-18.09.1-3.el7.x86_64"
    n: chirag
    default_container_name: webserver
    default_container_image: httpd:latest

  tasks:
  - name: "Docker"
    yum_repository:
        name: docker
        description: docker YUM repo
        baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
        gpgcheck: no

  - package:
      name: "{{ pname }}"
      state: present

  - name: Install Docker Module for Python
    pip:
      name: docker-py

  - service:
      name: "docker"
      state: started 

  - name: Pull default Docker image
    docker_image:
      name: "{{ default_container_image }}"
      source: pull

  - copy:
      src: "index.html"
      dest: "/root/html"
    ignore_errors: yes

  - name: Create default containers
    docker_container: 
      name: "{{ default_container_name }}"
      image: "{{ default_container_image }}"
      state: present
      exposed_ports:
       - 80/tcp
      published_ports:
       - 0.0.0.0:8086:80/tcp
      volumes:
       - /root/html/:/usr/local/apache2/htdocs/

